# Generated by Django 5.0.7 on 2024-08-01 22:17

import API.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='image',
            field=models.ImageField(null=True, upload_to=API.helpers.SaveMedia.save_book_image_path),
        ),
    ]
